-- Default ignore patterns for Clod uploader
-- These patterns specify which files to ignore when uploading to Claude

{ textPatterns = 
  [ "*.dll"
  , "*.dylib"
  , "*.exe"
  , "*.gif"
  , "*.ico"
  , "*.jar"
  , "*.jpg"
  , "*.jpeg"
  , "*.mp3"
  , "*.mp4"
  , "*.png"
  , "*.so"
  , "*.svg"
  , "*.tar.gz"
  , "*.zip"
  , ".clod"
  , ".git"
  , "build"
  , "dist"
  , "node_modules"
  , "out"
  , "target"
  , "*.log"
  , "Cargo.lock"
  , "package-lock.json"
  , "pnpm-lock.yaml"
  , "yarn.lock"
  , ".gitignore"
  , ".clodignore"
  ]
}